### ISSUE TITLE
Create 5 Users Stories Persona 1: Emily

### ISSUE THREAD

**Issue by kaitlin31415** [kaitlin31415/BCI4KidsMediapipe#2]
See issue #26 for Mural link

**Comment by PriyavartRajain** [comment]
Being someone who can only respond using gestures like eye and facial movement, my responses should be conveyed accurately within an acceptable delay. 
Emily hears what David says and responds with an eye movement. The gesture is reported as a Yes or a No within 1 minute using speech, which extends Emily's capability as now, she does not need David to stand right next to her in order to monitor her response. 
If the response was reported incorrectly, Emily can easily nullify the response and try again. This eliminates the possibility of a wrong interpretation of her response by David which used to be very frustrating for her. 
She also has the freedom to conversate with people who are unaware of how to read her gestures, which earlier required assistance from David.
